name: Deploy React Site

on:
  push:
    branches:
      - main
  workflow_dispatch:   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install Dependencies
      run: npm install
        
    - name: Build
      run: npm run build -- --outDir=./dist
      
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: ./dist
        
  deploy:

    needs: build
    
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/download-artifact@master
      with:
        name: dist
        
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./dist
